### ISSUE TITLE
Gainers & gap up/down scanner

### ISSUE THREAD

**Issue by Zainpro** [shner-elmo/TradeZero_API#1]
Nice app! This is a request. Would you care adding a gainers or gap up/down scanner?

**Comment by shner-elmo** [comment]
Hey Zain, as far as I know TradeZero dosent have that scanner integrated onto their web-app,  but its definetly possible to add it via a Rest API call to a website that has the scanner (like TradingView).
Stay tuned I will add this feature in the coming days.
Shner,

**Comment by shner-elmo** [comment]
Hey I added the scanner to a seperate repo:
https://github.com/shner-elmo/TradingView-Scanner

**Comment by Zainpro** [comment]
Great! However I have not seen the TZ api anywhere! Is that  TradingView a Realtime scanner?

**Comment by shner-elmo** [comment]
I made two separate repositories, [here](https://github.com/shner-elmo/TradeZero_API) you can find the TZ Api, and [here](https://github.com/shner-elmo/TradingView-Scanner) is the TV scanner, and yes it should be in real-time as TradingView offers real time data on Equities for free.
Although im not sure how often the scanner get updated, and if providing youre cookies will allow you to get updates more frequently. I will drop some tests in the TVScanner repo when I have time.

If you like any of my repositories you can leave a star to save them, and if you have any questiong about the scanner please open an issue in its respective repository, Thanks
Shner
