### ISSUE TITLE
Hard to borrow stock

### ISSUE THREAD

**Issue by BogDon9** [shner-elmo/TradeZero_API#10]
Does this work for shorting hard to borrow stock? Could you give an example if so? Also, is there a way to set a limit order for the sell to open that includes the fees associated with locating the shares? Or do you look up the fees in a different step? Thanks in advance for any help you can provide.

**Comment by shner-elmo** [comment]
Of course it does, that's one of the main reasons why this exists.
Have a look at the documentation, for locating hard to borrow stocks:
https://shner-elmo.github.io/tradezero-api/tradezero_api/main.html#TradeZero.locate_stock
And for limit orders:
https://shner-elmo.github.io/tradezero-api/tradezero_api/main.html#TradeZero.limit_order

**Comment by shner-elmo** [comment]
And you have to locate the shares prior to setting the limit order ofc
