### ISSUE TITLE
Portfolio.invested(symbol)

### ISSUE THREAD

**Issue by gonzas** [shner-elmo/TradeZero_API#4]
Hi, 
Think I found a bug in your code regarding function "Portfolio.invested(symbol_name)"
It only works when the account already have a position on that symbol, otherwise it fails always with something like this log.

```
Traceback (most recent call last):
  File "c:\Users\gonza\Documents\tradezero-api\tradezero_api\tz.py", line 22, in <module>
    if  (tz.Portfolio.invested(symbol_name)):
  File "C:\Users\gonza\Documents\tradezero-api\tradezero_api\portfolio.py", line 58, in invested
    data = self.portfolio('dict')
  File "C:\Users\gonza\Documents\tradezero-api\tradezero_api\portfolio.py", line 33, in portfolio
    df.columns = [
  File "c:\Users\gonza\Documents\tradezero-api\.venv\lib\site-packages\pandas\core\generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "c:\Users\gonza\Documents\tradezero-api\.venv\lib\site-packages\pandas\core\generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "c:\Users\gonza\Documents\tradezero-api\.venv\lib\site-packages\pandas\core\internals\managers.py", line 230, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "c:\Users\gonza\Documents\tradezero-api\.venv\lib\site-packages\pandas\core\internals\base.py", line 70, in _validate_set_axis
    raise ValueError(
```
**ValueError: Length mismatch: Expected axis has 1 elements, new values have 11 elements**

I have been triying to fix it for weeks to later do a pull request to you, but no results.
Could you guide me or give me some clues to fix this ?

Thank you!

**Comment by shner-elmo** [comment]
Hey, can you post the snippet of your code thas causing the error (and the full traceback if you left anything out), thanks

**Comment by gonzas** [comment]
This code works as it should be but only when there is a position, after execution, or when starts on no position, fails with the full log I posted before.

```
import time 
from tradezero_api import TradeZero
from tradezero_api import Order

tz = TradeZero(user_name='User', password='Passdw')
tz.login()

symbol_name="UCAR"
quantity=50
offset=0.10
high=10.21
low=1.51

while (True):
    # Verifico que la sesion no haya caducado y de lo contrario vuelvo a loguear
    if not tz.conn():
        tz.login()
    
    # Solo actuo cuando tengo una posicion abierta 
    if  (tz.Portfolio.invested(symbol_name)):
        ticker = tz.data(symbol_name)
        # Valido que el mercado no este cerrado (el precio es 0)
        if (ticker.last != 0):
            print(f"last: {ticker.last}, Quantity {quantity}, High: {high}, Low: {low}")

            if (str({ticker.last}) >= str({high})):
                tz.limit_order(Order.COVER, symbol_name, quantity, high+offset)   
            if (str({ticker.last}) <= str({low})):
                tz.limit_order(Order.COVER, symbol_name, quantity, low)
            else:
                print("Market Closed")
        else:
            print("No position on: SYMBOL")

    time.sleep(5)
```

**Comment by shner-elmo** [comment]
I see, the error happened when renaming the columns, this is probably because `df.columns` got a list of strings that has more names the actual column names, I can't debug this right now, but if you can run the following piece of code twice:
```py
# insert this code after creating the `tz` instance, and before closing the connection
import pandas as pd
df = pd.read_html(tz.driver.page_source, attrs={'id': 'opTable-1'})[0]
print(df.columns)
```

Run that code once with the window maximized fullscreen, and the 2nd time with the window only occupying half of the screen space, if you can send me the output (the column names) I will fix this bug.

**Comment by gonzas** [comment]
I put the import at the top, and the df after first login and it fails the same way, the browser chashes inmediatly (the logs remains the same too).

However think I got what your saying, maybe the debug that we want to see could be done like this too with "chropath" extension for chrome and using the xpath selector from portfolio function.

![image](https://github.com/shner-elmo/tradezero-api/assets/2583937/0b9c43bd-06dd-4ec1-9d28-22f1c3f3d447)

Could the string "You have no open positions." causing this issue maybe ?

**Comment by gonzas** [comment]
Are we on the right track to fix this ?

**Comment by shner-elmo** [comment]
I think you're right, this happens when there are no open positions and the table only has 1 column in the HTML.

It seems like [this](https://github.com/shner-elmo/tradezero-api/blob/master/tradezero_api/portfolio.py#L27-L30) piece of code is faulty, it should be updated to return `None` (or an empty DataFrame) when there are no open positions.

If you want to fix that, feel free to create a pull request with the updated code

**Comment by jegauth** [comment]
I got the same issue right now with the piece of code

```
from tradezero_api import TradeZero
import json

# Read the configuration file
with open("config.json") as f:
    config = json.load(f)

# Access the values from the configuration
username = config["tradezero"]["username"]
password = config["tradezero"]["password"]

tz = TradeZero(user_name=username, password=password)
tz.login(True)

print(f"I have invested in UCAR: {tz.Portfolio.invested('UCAR')}")
```

@shner-elmo I think you should devote a bit more time on that task

**Comment by jegauth** [comment]
A solution could be this: 

From `portfolio.py`:

```
    def invested(self, symbol):
        """
        returns True if the given symbol is in portfolio, else: false

        :param symbol: str: e.g: 'aapl', 'amd', 'NVDA', 'GM'
        :return: bool
        """
        data = self.portfolio('dict')

        if data is None:
            print('Portfolio is empty')
            return False

        symbols_list = list(data.keys())

        if symbol.upper() in symbols_list:
            return True
        return False
```

and

```
    def portfolio(self, return_type: str = 'df'):
        """
        return the Portfolio table as a pandas.DataFrame or nested dict, with the symbol column as index.
        the column names are the following: 'type', 'qty', 'p_close', 'entry',
        'price', 'change', '%change', 'day_pnl', 'pnl', 'overnight'
        note that if the portfolio is empty Pandas won't be able to locate the table,
        and therefore will return None

        :param return_type: 'df' or 'dict'
        :return: pandas.DataFrame or None if table empty
        """
        portfolio_symbols = self.driver.find_elements(By.XPATH, '//*[@id="opTable-1"]/tbody/tr/td[1]')
        df = pd.read_html(self.driver.page_source, attrs={'id': 'opTable-1'})[0]
        if len(portfolio_symbols) == 0 or df.loc[0, 0] == "You have no open positions.":
            warnings.warn('Portfolio is empty')
            return None

        df.columns = [
            'symbol', 'type', 'qty', 'p_close', 'entry', 'price', 'change', '%change', 'day_pnl', 'pnl', 'overnight'
        ]
        df = df.set_index('symbol')
        if return_type == 'dict':
            return df.to_dict('index')
        return df
```

@shner-elmo Are you ok with that solution?

**Comment by shner-elmo** [comment]
@jegauth Even two tabs on the same browser and same device are considered as two separate instances, and will get you disconnected...

**Comment by shner-elmo** [comment]
@jegauth Great solution.

Just remove the print statement because it's already gonna be printed from calling `portfolio()`:
```py
print('Portfolio is empty')
```
And update this line to compare the normalized string (which should be more reliable in the long-term):
```py
if len(portfolio_symbols) == 0 or df.loc[0, 0].lower() == "you have no open positions.":
```

Feel free to create a pull-request with the updated code.

**Comment by jegauth** [comment]
I am not going to make a pull request. I am going to leave you the choose to add it yourself or not. Feel free to do whatever you want with it

**Comment by gonzas** [comment]
> I think you should devote a bit more time on that task

Thanks @jegauth , I tested your code and works like a charm.

**Comment by jegauth** [comment]
@shner-elmo It is nice that you did this repo? Why did you do it? Do you automate some trades?
