### ISSUE TITLE
Connect and disconnect very quickly

### ISSUE THREAD

**Issue by jegauth** [shner-elmo/TradeZero_API#6]
When I run this:

from tradezero_api import TradeZero

tz = TradeZero(user_name='username', password='password')
tz.login(True)

tz.conn(True)

It loads fine, but eventually just a second or two later it disconnect and the browser shut down. Why does it produce that?

**Comment by shner-elmo** [comment]
Perhaps, you are using TradeZero from multiple devices? or you are creating multiple instances?

Because if you connect with the API, but open it also in another tab, or on your phone, it will disconnect the API since it can have only one instance open at a time.

**Comment by jegauth** [comment]
The thing is when I connect manually with the same website, the browser stays opened. When I run the code, the browser closed quite rapidly. So not sure it is a multiple devices issue.

**Comment by shner-elmo** [comment]
@jegauth Even two tabs on the same browser and device are considered separate instances and will get you disconnected...
