### ISSUE TITLE
Order Confirmation

### ISSUE THREAD

**Issue by jegauth** [shner-elmo/TradeZero_API#8]
Hello! It is asked to confirm an order when I place a market or limit order. 

![image](https://github.com/shner-elmo/tradezero-api/assets/116890061/c01c953e-1fa2-435f-9f23-4f1f7ee2fe2b)

How can I confirm that automatically using your module?

Thanks in advance!

**Comment by shner-elmo** [comment]
Whats up bro! You can disable the order confirmation altogether from the settings, is that what you want?

**Comment by jegauth** [comment]
Yes, it uses cache. So if I run the code on a different computer, I would have to deal with that problem again.

**Comment by shner-elmo** [comment]
@jegauth I see now. There isn't a method within the API to do it as of yet, but I think it can be easily added.

If you want to work on it then I suggest you open a pull request, and start by finding the ID/Xpath to the `confirm` button, I can help you from there.

**Comment by shner-elmo** [comment]
Hey @jegauth have you made any progress on the issue?
